server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.92.129:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false

logging:
  config: classpath:logback-prd-boot.xml

system:
  addr: http://localhost/Internet-advert-web/
  swagger:
    enable: true